variables:
  GIT_DEPTH: 1

cache:
  key: "vue-blog"
  untracked: true
  paths:
    - ./dist
    - ./docker-compose.yml

stages:
  - build
  - make

upload_to_oss:
  image: node:alpine
  stage: build
  script:
    - npm install --registry https://registry.npm.taobao.org
    - npm run build

make_image:
  image: docker:stable
  stage: make
  script:
    - sed -i "s/blog:\w\+-FE/blog:$CI_COMMIT_SHORT_SHA-FE/g" docker-compose.yml
    - docker login -u="$DOCKER_USERNAME_ALI" -p="$DOCKER_PASSWORD_ALI" $DOCKER_REPOSITORY_ALI
    - docker build
      -t $DOCKER_REPOSITORY_ALI/calabash/blog:$CI_COMMIT_SHORT_SHA-FE
      -f ./Dockerfile .
    - docker push $DOCKER_REPOSITORY_ALI/calabash/blog:$CI_COMMIT_SHORT_SHA-FE
    - scp ./docker-compose.yml deploy-server:~/deploy/blog/fe -P $SSH_PORT
    - ssh deploy-server -p $SSH_PORT "cd ~/deploy/blog/fe && docker-compose up -d"




