image: docker:stable

services:
  - docker:dind
  
stages:
 - build
 - make_image
 - deploy
  
  
build:
  image: node:latest
  stage: build
  cache:
    untracked: true
    paths:
      - node_modules/
  script:
    - npm install --registry https://registry.npm.taobao.org
    - npm run build
    
make:
  image: docker:stable
  stage: make_image
  before_script:
    - dockerd --registry-mirror https://g1qu6uyv.mirror.aliyuncs.com
    - docker info
  script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t caaalabash/vue-blog:$CI_COMMIT_SHORT_SHA ./server
    - docker push caaalabash/vue-blog:$CI_COMMIT_SHORT_SHA

deploy_test:
  image: caaalabash/alpine-ssh:latest
  stage: deploy
  before_script:
    - echo "$SSH_PRIVATE_KEY" > id_rsa_2048
    - chmod 0600 id_rsa_2048
    - eval $(ssh-agent)
    - ssh-add id_rsa_2048
   
  script:
    - ssh -p 15678 root@$DEPLOY_SERVER "/mynode/vue-blog-ci/deploy/startup.sh $CI_COMMIT_SHORT_SHA"