language: node_js

sudo: false

cache:
  - npm
  - yarn

os:
  - linux

services:
  - docker

node_js:
  - '10'

notifications:
  email:
    on_failure: always

addons:
  ssh_known_hosts: 60.205.219.85

before_install:
  - openssl aes-256-cbc -K $encrypted_a6ef41ff4c30_key -iv $encrypted_a6ef41ff4c30_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - chmod 777 ./deploy/startup.sh

script:
  - npm run build
  # 将相关文件拷贝到服务器
  - scp -P 15678 -o StrictHostKeyChecking=no -r -p ./deploy/* root@60.205.219.85:/mynode/vue-blog-ci/deploy
  - scp -P 15678 -o StrictHostKeyChecking=no -p ./blog.conf root@60.205.219.85:/alidata/server/nginx/conf/vhosts
  - scp -P 15678 -o StrictHostKeyChecking=no -p ./dist/robots.txt ./dist/index.html ./dist/service-worker.js ./dist/manifest.json root@60.205.219.85:/mynode/vue-blog-ci/dist
  # 上传镜像
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t caaalabash/vue-blog:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID-BE ./server
  - docker push caaalabash/vue-blog:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID-BE

after_success:
  # 执行服务器脚本 传递构建Id
  - ssh -p 15678 root@60.205.219.85 -o StrictHostKeyChecking=no "/mynode/vue-blog-ci/deploy/startup.sh $TRAVIS_BRANCH-$TRAVIS_BUILD_ID"
