
export const SET_CURRENT_BLOG_LIST = 'SET_CURRENT_BLOG_LIST';

export const SET_USER = 'SET_USER';

export const LOG_OUT = 'LOG_OUT';

export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';

export const OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG';

export const CREATE_NEW_IDEA = 'CREATE_NEW_IDEA';

export const CHANGE_IDEA = 'CHANGE_IDEA';

export const GET_IDEA = 'GET_IDEA';

export const GET_USER_INFO= 'GET_USER_INFO';

export const CHANGE_USER_INFO = 'CHANGE_USER_INFO';

export const GET_IDEA_LIST = 'GET_IDEA_LIST';

export const DELETE_IDEA = 'DELETE_IDEA';

export const REDIRECT_TO = 'REDIRECT_TO';

export const BACK_INDEX =  'BACK_INDEX';

export const LOAD_MORE = 'LOAD_MORE';

export const SET_TOKEN = 'SET_TOKEN';

export const SET_LIKELIST = 'SET_LIKELIST';

export const SET_AVATAR = 'SET_AVATAR';

export const SET_COMMENT_LIST = 'SET_COMMENT_LIST'

export const SOCKET_CONNECT = 'SOCKET_CONNECT'

export const SOCKET_SEND_MSG = 'SOCKET_SEND_MSG'

export const SET_CHAT_DATA = 'SET_CHAT_DATA'

export const SOCKET_RECVMSG = 'SOCKET_RECVMSG'

export const SET_CANVAS_LINECOLOR = 'SET_CANVAS_LINECOLOR'

export const SET_COLLECTLIST = 'SET_COLLECTLIST'

export const ADD_COLLECTLIST = 'ADD_COLLECTLIST'

export const ADD_BLOG_TO_COLLECT = 'ADD_BLOG_TO_COLLECT'

export const DELETE_COLLECT = 'DELETE_COLLECT'

export const DELETE_COLLECT_BLOG = 'DELETE_COLLECT_BLOG'
