export default {
    SET_CURRENT_BLOG_LIST: 'SET_CURRENT_BLOG_LIST',
    SET_USER: 'SET_USER',
    LOG_OUT: 'LOG_OUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    OPEN_LOGIN_DIALOG: 'OPEN_LOGIN_DIALOG',
    CREATE_NEW_IDEA: 'CREATE_NEW_IDEA',
    CHANGE_IDEA: 'CHANGE_IDEA',
    GET_IDEA: 'GET_IDEA',
    GET_USER_INFO: 'GET_USER_INFO',
    CHANGE_USER_INFO: 'CHANGE_USER_INFO',
    GET_IDEA_LIST: 'GET_IDEA_LIST',
    DELETE_IDEA: 'DELETE_IDEA',
    /*
    REQUEST_ERR :'REQUEST_ERR'*/
    REDIRECT_TO: 'REDIRECT_TO',
    BACK_INDEX: 'BACK_INDEX'
};
