version: "3"

services:
  blog_backend:
    image: registry.cn-beijing.aliyuncs.com/calabash/blog:${VUE_BLOG_TAG}-BE
    container_name: blog-backend
    ports:
      - 8887:3000
    network_mode: bridge
    restart: unless-stopped
    env_file:
      - /mynode/vue-blog-ci/vue-blog.env
    volumes:
      - /etc/localtime:/etc/localtime
      - /alidata/www/blog/img:/data/img
      - /alidata/www/blog/blob:/data/blob
      - /mynode/vue-blog-ci/sitemap:/data/sitemap
    extra_hosts:
      - "dockerhost:172.17.0.1"
  blog_frontend:
    image: registry.cn-beijing.aliyuncs.com/calabash/blog:${VUE_BLOG_TAG}-FE
    container_name: blog-frontend
    ports:
      - 8888:800
    network_mode: bridge
    restart: unless-stopped
    extra_hosts:
      - "dockerhost:172.17.0.1"
