version: "3"
services:
  backend:
    image: registry.cn-beijing.aliyuncs.com/calabash/blog:${VUE_BLOG_TAG}-BE
    container_name: blog-backend
    ports:
      - 3000:3000
      - 8888:800
    env_file:
      - /mynode/vue-blog-ci/vue-blog.env
    volumes:
      - /etc/localtime:/etc/localtime
      - /alidata/www/blog/img:/data/img
      - /alidata/www/blog/blob:/data/blob
      - /mynode/vue-blog-ci/sitemap:/data/sitemap
    network_mode: bridge
    restart: unless-stopped
    external_links:
      - myMongoDB
      - myRedis
  frontend:
    image: registry.cn-beijing.aliyuncs.com/calabash/blog:${VUE_BLOG_TAG}-FE
    container_name: blog-frontend
    restart: unless-stopped
    network_mode: "service:backend"
