version: "3"
services:
  frontend:
    image: caaalabash/vue-blog:${VUE_BLOG_TAG}-FE
    container_name: blog-frontend
    ports:
      - 8888:800
    restart: unless-stopped
    network_mode: container: blog-backend