version: "3"
services:
  frontend:
    image: caaalabash/vue-blog:${VUE_BLOG_TAG}-FE
    container_name: blog-frontend
    network_mode: host
    restart: unless-stopped
    volumes:
      - /mynode/vue-blog-ci/ssl:/app/ssl
      - /alidata/www/blog/img:/app/img
  backend:
    image: caaalabash/vue-blog:${VUE_BLOG_TAG}-BE
    container_name: blog-backend
    ports:
      - 3000:3000
    env_file:
      - /mynode/vue-blog-ci/vue-blog.env
    volumes:
      - /etc/localtime:/etc/localtime
      - /alidata/www/blog/img:/data/img
      - /alidata/www/blog/blob:/data/blob
    network_mode: bridge
    restart: unless-stopped
    external_links:
      - myMongoDB
      - myRedis
