export const SET_USER = 'SET_USER'

export const LOG_OUT = 'LOG_OUT'

export const REDIRECT_TO = 'REDIRECT_TO'

export const SET_USER_INFO= 'SET_USER_INFO'

export const SET_LIKELIST = 'SET_LIKELIST'

export const SET_AVATAR = 'SET_AVATAR'

export const SET_COLLECTLIST = 'SET_COLLECTLIST'

export const ADD_COLLECTLIST = 'ADD_COLLECTLIST'

export const ADD_BLOG_TO_COLLECT = 'ADD_BLOG_TO_COLLECT'

export const DELETE_COLLECT = 'DELETE_COLLECT'

export const DELETE_COLLECT_BLOG = 'DELETE_COLLECT_BLOG'

export const SET_CHAT_DATA = 'SET_CHAT_DATA'

export const SOCKET_CONNECT = 'SOCKET_CONNECT'

export const SOCKET_SENDMSG = 'SOCKET_SENDMSG'

export const SOCKET_RECVMSG = 'SOCKET_RECVMSG'

export const SET_VIEW_COUNT = 'SET_VIEW_COUNT'
